server:
  port: 8300

spring:
  application:
    name: UTIL
  cloud:
    nacos:
      server-addr: 106.12.109.2:8848
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/community?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    user: info

#设置openfeign调用超时
feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000